# Generated by Django 5.1.3 on 2025-11-24 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_delete_promocode_book_is_paid_book_preview_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MAIBSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test/Sandbox'), ('production', 'Production')], default='test', max_length=20)),
                ('project_id', models.CharField(help_text='MAIB Project ID', max_length=255)),
                ('project_secret', models.CharField(help_text='MAIB Project Secret', max_length=255)),
                ('signature_key', models.CharField(help_text='Signature Key for callback validation', max_length=255)),
                ('api_base_url', models.URLField(default='https://api.maibmerchants.md/v1')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MAIB Settings',
                'verbose_name_plural': 'MAIB Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MDL', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Successful'), ('FAIL', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('pay_id', models.CharField(blank=True, help_text='Transaction ID from MAIB', max_length=255, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, help_text='Our order ID sent to MAIB', max_length=255, null=True)),
                ('pay_url', models.URLField(blank=True, help_text='Payment URL from MAIB', null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('rrn', models.CharField(blank=True, help_text='Retrieval Reference Number', max_length=50, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, help_text='Masked card number', max_length=20, null=True)),
                ('three_ds', models.CharField(blank=True, help_text='3D Secure status', max_length=10, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('request', 'API Request'), ('response', 'API Response'), ('callback', 'Callback'), ('error', 'Error'), ('info', 'Info')], max_length=20)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'book', 'status'], name='payments_pa_user_id_2cff5c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pay_id'], name='payments_pa_pay_id_b264fa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
