# Generated by Django 5.1.3 on 2025-01-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(upload_to='files/articles')),
                ('publication_date', models.DateField(auto_now_add=True, null=True)),
                ('author', models.CharField(choices=[('Tudor Osoianu', 'Tudor Osoianu'), ('Dinu Ostavciuc', 'Dinu Ostavciuc'), ('Tudor Osoianu, Dinu Ostavciuc', 'Tudor Osoianu, Dinu Ostavciuc')], max_length=256)),
                ('category', models.CharField(blank=True, choices=[('procedura_penala', 'Procedura Penală'), ('criminalistica', 'Criminalistica'), ('alte_stiinte', 'Alte Științe')], max_length=50, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
            },
        ),
    ]
