# Generated by Django 3.2.12 on 2024-10-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(upload_to='files/articles')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('author', models.CharField(choices=[('TO', 'Tudor Osoianu'), ('DO', 'Dinu Ostavciuc'), ('TD', 'Tudor Osoianu, Dinu Ostavciuc')], max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
            },
        ),
    ]
