# Generated by Django 5.1.3 on 2025-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[('Tudor Osoianu', 'Tudor Osoianu'), ('Dinu Ostavciuc', 'Dinu Ostavciuc'), ('Tudor Osoianu, Dinu Ostavciuc', 'Tudor Osoianu, Dinu Ostavciuc'), ('Tudor Osoianu, Dumitru Calendari', 'Tudor Osoianu, Dumitru Calendari')], max_length=256),
        ),
    ]
