# Generated by Django 5.1.3 on 2026-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Краткий отрывок для превью на странице', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_content',
            field=models.TextField(blank=True, help_text='HTML версия статьи для SEO (будет видна Google)', null=True),
        ),
    ]
