# Generated by Django 5.1.3 on 2024-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20241019_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('procedura_penala', 'Procedura Penală'), ('criminalistica', 'Criminalistica'), ('alte_stiinte', 'Alte Științe')], max_length=50, null=True),
        ),
    ]
