# Generated by Django 5.1.3 on 2026-04-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_slug_unique'),
        ('articles', '0004_seed_seo_excerpts'),
    ]

    operations = [
    ]
