# Generated by Django 5.1.3 on 2024-11-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(choices=[('Tudor Osoianu', 'Tudor Osoianu'), ('Dinu Ostavciuc', 'Dinu Ostavciuc'), ('Tudor Osoianu, Dinu Ostavciuc', 'Tudor Osoianu, Dinu Ostavciuc')], max_length=200)),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cărți',
            },
        ),
    ]
