# Generated by Django 5.1.3 on 2025-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AddField(
            model_name='book',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Check if this book requires payment'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Optional preview file for paid books', null=True, upload_to='books/previews/'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in MDL (0 for free books)', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
