# Generated by Django 5.1.3 on 2024-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_promocode_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
