# Generated by Django 5.1.3 on 2025-12-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_promocode_book_is_paid_book_preview_file_and_more'),
        ('books', '0002_delete_promocode_delete_subscription'),
    ]

    operations = [
    ]
