# Generated by Django 5.1.3 on 2024-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_file_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('procedura_penala', 'Procedura Penală'), ('criminalistica', 'Criminalistica'), ('alte_stiinte', 'Alte Științe')], default='Procedura Penala', max_length=50),
        ),
    ]
