# Generated by Django 5.1.3 on 2025-01-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Noutate',
                'verbose_name_plural': 'Noutăți',
            },
        ),
    ]
