# Generated by Django 5.1.3 on 2024-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
