# Generated by Django 5.1.3 on 2025-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Главное изображение (опционально)', null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения (0, 1, 2...)'),
        ),
    ]
