# Generated by Django 5.1.3 on 2025-01-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_content'),
        ('main', '0004_alter_news_image'),
    ]

    operations = [
    ]
